# Generated by Django 4.1.5 on 2023-01-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('phone', models.PositiveIntegerField(verbose_name='Phone')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('address', models.CharField(max_length=80, verbose_name='Address')),
                ('company', models.CharField(max_length=30, verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
